version: "3"

services:
  app:
    build:
      context: ""
      dockerfile: Dockerfile
    restart: always
    depends_on:
      - postgres
    environment:
      SPRING_DATASOURCE_URL: jdbc:postgresql://localhost:5432/postgres?useSSL=false
      SPRING_DATASOURCE_USERNAME: postgres
      SPRING_DATASOURCE_PASSWORD: postgres
    ports:
      - 8080:8080

  postgres:
    image: postgres:13
    container_name: "postgres_database"
    restart: always
    ports:
      - 5432:5432
    environment:
      POSTGRES_USER: "postgres"
      POSTGRES_DB: "db"
      POSTGRES_PASSWORD: "postgres"
      PGDATA: "/var/lib/postgresql/data/pgdata"
      volumes:
        "db-data:/var/lib/postgresql/data"

volumes:
  db-data: