-- migration 1 date: 22.03.2023

CREATE TABLE IF NOT EXISTS public.role_table1
(
    id int NOT NULL GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    name varchar(50) NOT NULL
    );

insert into role_table1(name) values ('ROLE_ADMIN');
insert into role_table1(name) values ('ROLE_MODERATOR');
insert into role_table1(name) values ('ROLE_SUPPLIER');
insert into role_table1(name) values ('ROLE_KEYMANAGER');
insert into role_table1(name) values ('ROLE_SHOP');
insert into role_table1(name) values ('ROLE_USER');


CREATE TABLE IF NOT EXISTS public.activity_table1
(
    id int NOT NULL GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    activity_time timestamp with time zone NOT NULL,
    activity_type varchar(50) NOT NULL,
    user_id int NOT NULL,
    activity_message varchar(3000) NOT NULL
);


CREATE TABLE IF NOT EXISTS public.user_table1
(
    id int NOT NULL GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    login varchar(100) NOT NULL,
    password varchar(500) NOT NULL,
    email varchar(100),
    full_name varchar(100),
    company_name varchar(100),
    phone_number varchar(100),
    address varchar(500),
    certain_place_address varchar(500),
    appAccess varchar(50),
    role_id  integer,
    registration_time timestamp with time zone,
    enabled boolean
);

CREATE TABLE IF NOT EXISTS public.online_user_table1
(
    user_id int NOT NULL PRIMARY KEY,
    last_ping_time timestamp with time zone NOT NULL
);


CREATE TABLE IF NOT EXISTS public.users_receipt_summary1
(
    id int NOT NULL GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    activity_time timestamp with time zone NOT NULL,
    user_id int NOT NULL,
    company_name varchar(100),
    certain_place_address varchar(500),
    type varchar(200) NOT NULL,
    materials varchar(1000) NOT NULL,
    material_price double precision NOT NULL,
    add_price double precision NOT NULL,
    all_price double precision NOT NULL,
    main_coeff double precision NOT NULL,
    material_coeff double precision NOT NULL,
    slabs double precision NOT NULL,
    product_square double precision NOT NULL
);

CREATE TABLE IF NOT EXISTS public.shops_and_users_table1
(
    id int NOT NULL GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    shop_id int NOT NULL,
    user_id int NOT NULL
);

CREATE TABLE IF NOT EXISTS public.managers_users_table1
(
    id int NOT NULL GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    key_manager_id int NOT NULL,
    user_id int NOT NULL
);

CREATE TABLE IF NOT EXISTS public.user_refresh_table1
(
    id int NOT NULL GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    user_id int NOT NULL,
    refresh_token varchar(100) NOT NULL
    );

CREATE TABLE IF NOT EXISTS public.uploadedfiles1
(

    id          int NOT NULL GENERATED BY DEFAULT AS IDENTITY,
    name        varchar(200),
    path        varchar(300),
    url         varchar(400),
    uploadDate  timestamp with time zone,
    size        bigint,
    hashcode    int,
    info        varchar(1000),
    for_clients varchar(500),
    author_id   int,
    PRIMARY KEY (id)
    );

CREATE TABLE  IF NOT EXISTS public.pricelist_table1
(
    id         int NOT NULL GENERATED BY DEFAULT AS IDENTITY,
    name       varchar(200),
    path       varchar(300),
    url        varchar(400),
    uploadTime timestamp with time zone NOT NULL,
                             info        varchar(1000),
    for_clients varchar(500),
    author_id   int,
    PRIMARY KEY (id)
    );

CREATE TABLE IF NOT EXISTS public.statistics_table1
(
    id bigint NOT NULL GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    time_slice timestamp with time zone NOT NULL,
    users_online int NOT NULL,
    new_receipts int NOT NULL,
    new_users int NOT NULL
);

-- insert data to activity_table1
insert into activity_table1(id, activity_time, activity_type, activity_message, user_id)
    select activity_table.id,activity_table.activity_time,activity_table.activity_type,
        activity_table.activity_message, case WHEN user_table.id is NULL then 1 else user_table.id end
        from activity_table left join user_table ON activity_table.login = user_table.login;

-- insert data to user_table1
insert into user_table1(id, login, password, email, full_name, company_name, phone_number, address,
    certain_place_address, appaccess, role_id, registration_time, enabled)
    select user_table.id,user_table.login,user_table.password,user_table.email,
        user_table.full_name,user_table.company_name,user_table.phone_number,user_table.address,
        user_table.certain_place_address,user_table.appaccess,user_table.role_id, null ,user_table.enabled
        from user_table;

-- insert data to online_user_table1
insert into online_user_table1(user_id, last_ping_time)
    select user_id, last_ping_time from online_user_table;

-- insert data to users_receipt_summary1
insert into users_receipt_summary1(id, activity_time, user_id, company_name, certain_place_address, type, materials,
    material_price, add_price, all_price, main_coeff, material_coeff, slabs, product_square )
    select id, activity_time, user_id, company_name, certain_place_address, type, materials,
        material_price, add_price, all_price, main_coeff, material_coeff, slabs, product_square
        from users_receipt_summary;

-- insert data to uploadedfiles1
insert into uploadedfiles1(id, name, path, url, uploadDate, size, hashcode, info, for_clients, author_id)
select
    uploadedfiles.id,
    uploadedfiles.name,
    uploadedfiles.path,
    uploadedfiles.url,
    uploadedfiles.uploaddate,
    uploadedfiles.size,
    uploadedfiles.hashcode,
    uploadedfiles.info,
    uploadedfiles.for_clients,
    case WHEN user_table.id is NULL then 1 else user_table.id end

from uploadedfiles left join user_table ON uploadedfiles.author = user_table.login;

-- insert data to pricelist_table1
insert into pricelist_table1(id, name, path, url, uploadtime, info, for_clients, author_id)
select
    pricelist_table.id,
    pricelist_table.name,
    pricelist_table.path,
    pricelist_table.url,
    pricelist_table.uploadtime,
    pricelist_table.info,
    pricelist_table.for_clients,
    case WHEN user_table.id is NULL then 1 else user_table.id end

from pricelist_table left join user_table ON pricelist_table.author = user_table.login;

-- rename old tables:
ALTER TABLE online_user_table RENAME TO online_user_table_old;
ALTER TABLE pricelist_table RENAME TO pricelist_table_old;
ALTER TABLE role_table RENAME TO role_table_old;
ALTER TABLE uploadedfiles RENAME TO uploadedfiles_old;
ALTER TABLE user_table RENAME TO user_table_old;
ALTER TABLE users_receipt_summary RENAME TO users_receipt_summary_old;

-- rename new tables:
ALTER TABLE activity_table1 RENAME TO activity_table;
ALTER TABLE managers_users_table1 RENAME TO managers_users_table;
ALTER TABLE online_user_table1 RENAME TO online_user_table;
ALTER TABLE pricelist_table1 RENAME TO pricelist_table;
ALTER TABLE role_table1 RENAME TO role_table;
ALTER TABLE shops_and_users_table1 RENAME TO shops_and_users_table;
ALTER TABLE statistics_table1 RENAME TO statistics_table;
ALTER TABLE uploadedfiles1 RENAME TO uploadedfiles;
ALTER TABLE user_refresh_table1 RENAME TO user_refresh_table;
ALTER TABLE user_table1 RENAME TO user_table;
ALTER TABLE users_receipt_summary1 RENAME TO users_receipt_summary;