CREATE TABLE public.uploadedFiles
(
    id         int NOT NULL GENERATED BY DEFAULT AS IDENTITY,
    name       varchar(200),
    path       varchar(300),
    url        varchar(400),
    uploadDate date,
    size       bigint,
    hashcode   int,
    PRIMARY KEY (id)
);

CREATE TABLE public.pricelist_table
(
    id         int NOT NULL GENERATED BY DEFAULT AS IDENTITY,
    name       varchar(200),
    path       varchar(300),
    url        varchar(400),
    uploadTime timestamp with time zone NOT NULL,
    author     varchar(200),
    PRIMARY KEY (id)
);